import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Box, SimpleGrid, Heading, Center} from "@chakra-ui/react"
import MovieCard from './Components/MovieCard'
 
import axios from "axios"
import Navbar from './Components/Navbar'

export async function getServerSideProps() {
  const res=await axios.get(`http://localhost:8080/movie`);
  return {
    props: {
      data:res.data
    }
  }
}

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg='#000'>
        <Navbar />
        <Center>
        </Center>
        <SimpleGrid columns={3} w='80%' gap='20px' m='40px auto'>
        {
          data.map((item)=>
          <MovieCard key={item?.id} data={item} />
          )
        }
          </SimpleGrid>
      </Box>
    </>
  )
}
